### PR TITLE
Addressing Simplifier issues against Genomics IG

### PR DESCRIPTION
**Pull request by omarisgreat**
Updated status codes and updated descriptions within ServiceRequest fields

### CODE REVIEW

**Review by KazeemHamzat — COMMENTED** [review]
completed -typo

**Review by KazeemHamzat — COMMENTED** [review]
From NGTP, will implementer have clear knowledge that RemoteProcessingRequired vs RemoteGeneticDataProcessingRequired are two distinct status codes? Seem a similar scenario in my view.

**Review by KazeemHamzat — COMMENTED** [review]
Order Filler as an actor may raise a replacement request on an order. Does this still satisfy the position here? "The status is generally fully in the control of the requester"

**Review by KazeemHamzat — APPROVED** [review]

**Review by KazeemHamzat — APPROVED** [review]

**Review by KazeemHamzat — APPROVED** [review]

**Comment by omarisgreat** [comment]
> completed -typo

This is very odd, I have completed in my repo but in the diff on github it shows comleted. I'll merge in and correct directly on github if the issue persists

**Comment by omarisgreat** [comment]
> From NGTP, will implementer have clear knowledge that RemoteProcessingRequired vs RemoteGeneticDataProcessingRequired are two distinct status codes? Seem a similar scenario in my view.

I will pick this up with the GU and see whether larger descriptions are required

**Comment by omarisgreat** [comment]
> Order Filler as an actor may raise a replacement request on an order. LAB-2 (LTW) LAB-6 (LCC) Does this still satisfy the position here? "The status is generally fully in the control of the requester"

This text is coming directly from the HL7 international description. I only changed the links here but we will need to have a further think about this. i.e. the process for raising a new order. i.e. does the lab request the original ServiceRequest get suspended and ask for a new service request or do they cancel the order themselves.

**Pull request merged**
