### PR TITLE
Addition of Message Definitions and associated artifacts

### PR DESCRIPTION
**Pull request by omarisgreat**

### CODE REVIEW

**Review by KevinMayfield — COMMENTED** [review]
Can you remove the MessageHeader from focus. 

This is unnecessary as this is already a rule for FHIR Messages. Understand it is useful for a human reading the definition but technically it could lead to issues.

**Comment by omarisgreat** [comment]
@KevinMayfield, this has now been fixed. FYI, we will be looking to migrate some profiles into NHSD depending on guidance from the profiling workshop and KevS, so you can consider these placeholders to allow us to build up the Genomics IG for the time being.

**Review by KevinMayfield — COMMENTED** [review]
I don't think this is necessary as NHSDigital-MessageHeader is probably sufficient and I feel MessageHeader should be generic to allow middleware to handle messages independent of message content.

**Review by KevinMayfield — COMMENTED** [review]
Wrt to MedicationDefinitions

I think the optional focused items aren't necessary and may lead to conflicts with ServiceRequest profiles. 

For example to make a Patient mandatory in this message. I think the ServiceRequest-Genomics should have patient mandatory (aggregation = bundled). 
Patient does not need to be in the MessageDefinition.

The same would apply to all other resources (except for ServiceRequest)

**Comment by omarisgreat** [comment]
Hi @KevinMayfield, Regarding the Capability statement comment. I only have the MessageHeader profile to trial a different ValueSet for message event codes related to genomics. I'm intending to merge the ValueSet with the NHSD message-events ValueSet once the final list has been agreed by the Genomics Programme (so I've got it here for demo purposes). 

Regarding the rest of the CapabilityStatement, this was added to ensure the correct profiles are targeted during validation (and I am also planning some restful interactions which will not be using messages).

**Review by KevinMayfield — COMMENTED** [review]
I don't think we should have Message Event codesystem for genomics (well, in a genomics repo). 

The handling of messages should be generic to enable middleware to handle them.  So I would recommend either adding these codes to the NHS Digital Message Events Codesystem or moving this CodeSystem to NHS Digital IG.

**Comment by omarisgreat** [comment]
> I don't think we should have Message Event codesystem for genomics (well, in a genomics repo).
> 
> The handling of messages should be generic to enable middleware to handle them. So I would recommend either adding these codes to the NHS Digital Message Events Codesystem or moving this CodeSystem to NHS Digital IG.

Agreed, as mentioned in my other comment, I am just waiting on a finalised list of message types from Genomics before making the change in the NHSD repo (as I want to avoid multiple changes as codes change). The current system is for demo purposes until agreed by NHSE

**Comment by KevinMayfield** [comment]
Approved. 

Recommend the MessageDefinition and profiling discussion is added to Design Authority agenda.

**Review by KevinMayfield — APPROVED** [review]

**Comment by omarisgreat** [comment]
@KevinMayfield, I'll have a look at the MessageDefinitions and add in the aggregation (I'll need to have a think about the types of aggregation allowed as I want to allow some resources, such as ServiceRequest, used in multiple contexts (e.g. on initial request, the patient resource should be bundled but on status updates, I would like this referenced instead so a single resource can be sent instead of the full bundle)

**Pull request merged**
